prefix..'kcmds'
prefix.."newkl"
prefix..'iy' then -- the classic
prefix..'myvis'
prefix..'mydraw'
prefix..'cmdpi' then -- well, you need that visualiser, do you?
prefix..'prsc' then -- PR Script ~ atprog
prefix..'cmdy' then -- you don't need this for attaching anymore ;)
prefix..'tricky' then -- CREDITS TO TECH
prefix..'ilove' then -- CREDITS TO TECH
prefix..'wl'
prefix..'whitelist'
prefix..'unwl'
prefix..'unwhitelist'
prefix..'bl'
prefix..'blacklist'
prefix..'unbl'
prefix..'unblacklist'
prefix..'listwl'
prefix..'antimlog'
prefix..'unantimlog'
prefix..'admin'
prefix..'unadmin'
prefix..'listadmins'
prefix..'gearwl'
prefix..'ungearwl'
prefix..'listgearwl'
prefix..'fogvis' then -- fonalc funny var
prefix..'unfogvis' then -- fonalc funny var
prefix..'ccol'
prefix..'unccol'
prefix..'blwlan'
prefix..'unblwlan'
prefix..'loopkill'
prefix..'unloopkill'
prefix..'names'
prefix..'unnames'
prefix..'lagged'
prefix..'unlagged'
prefix..'report'
prefix..'checkperm'
prefix..'fcheckperm' then -- cool amirite
prefix..'checkpersons'
prefix..'checkgps'
prefix..'listbl'
prefix..'permusers'
prefix..'personsusers'
prefix..'adminjoy'
prefix..'slock'
prefix..'unslock'
prefix..'newplrslock'
prefix..'unnewplrslock'
prefix..'autoblvgc'
prefix..'unautoblvgc'
prefix..'npslist'
prefix..'plrnewlen'
prefix..'pboombox'
prefix..'mboombox'
prefix..'bgrange'
prefix..'lgmusic'
prefix..'unlgmusic'
prefix..'msay'
prefix..'unmsay'
prefix..'gmusic'
prefix..'rgmusic'
prefix..'nmusic' then -- if it double executes ... you
prefix..'pmusic' then -- if it double executes ... you
prefix..'musiclist'
prefix..'theme'
prefix..'themelist'
prefix..'gear'
prefix..'gearlist'
prefix..'char'
prefix..'charlist'
prefix..'turn'
prefix..'pausem'
prefix..'playm'
prefix..'stopm'
prefix..'startm'
prefix..'stops'
prefix..'starts'
prefix..'deiv' then -- ported from simplekah
prefix..'undeiv' then  -- ported from simplekah
prefix..'tropics' then  -- ported from simplekah
prefix..'sclr' then -- super clr fix everything (ffix does everything to yourself)
prefix..'volm' then -- rap e
prefix..'musicid'
prefix..'cmusicid'
prefix..'audiolog'
prefix..'unaudiolog'
prefix..'cvol'
prefix..'timepos'
prefix..'timeis'
prefix..'timedur'
prefix..'timeps'
prefix..'timeplay'
prefix..'audiolol'
prefix..'unaudiolol'
prefix..'antimusic'
prefix..'unantimusic'
prefix..'pmu'
prefix..'2pmu'
prefix..'bring'
prefix..'goto'
prefix..'song' then -- bit buggy if you stop the music but keep the playlist open
prefix..'ssong'
prefix..'esong'
prefix..'ggear'
prefix..'gchar' then -- tech added this command to scv3-var :)
prefix..'antiabuse'
prefix..'unantiabuse'
prefix..'bok'
prefix..'cgoto'
prefix..'fixbp'
prefix..'movebp'
prefix..'spawnkill'
prefix..'cagespawn'
prefix..'2fixpads'
prefix..'2fixreg'
prefix..'2fixbp'
prefix..'fcam'
prefix..'fixspawn'
prefix..'movespawn'
prefix..'fixregen'
prefix..'ivmove'
prefix..'omove'
prefix..'moveregen'
prefix..'saveregen'
prefix..'cusername'
prefix..'fixpads'
prefix..'movepads'
prefix..'fixfl'
prefix..'movefl'
prefix..'fixobby'
prefix..'moveobby'
prefix..'fixkb'
prefix..'movekb'
prefix..'fixobox'
prefix..'moveobox'
prefix..'fixadv'
prefix..'moveadv'
prefix..'fixhouse'
prefix..'movehouse'
prefix..'fixbb'
prefix..'movebb'
prefix..'toregen'
prefix..'rparts'
prefix..'lrobb'
prefix..'laobb'
prefix..'findregen' then -- i know it sucks but perm exists lol
prefix..'nofindregen'
prefix..'2findregen' then -- i know it sucks but perm exists lol
prefix..'2nofindregen'
prefix..'leakedreg' then -- i know it sucks but perm exists lol
prefix..'unpmu'
prefix..'offmusic'
prefix..'onmusic'
prefix..'remusic'
prefix..'equipall'
prefix..'actall'
prefix..'invall'
prefix..'dropall'
prefix..'vgcrash'
prefix..'cocrash'
prefix..'emcrash'
prefix..'pcrash'
prefix..'fcrash'
prefix..'dcrash'
prefix..'scrash' then -- not a silent crash!
prefix..'swc'
prefix..'unswc'
prefix..'rkick'
prefix..'unrkick'
prefix..'seedkick'
prefix..'meshkick' then  -- mesh kick haha
prefix..'hatkick' then  -- hat kick haha
prefix..'antimesh'
prefix..'unantimesh'
prefix..'antihat'
prefix..'unantihat'
prefix..'welmsg'
prefix..'unwelmsg'
prefix..'antian'
prefix..'unantian'
prefix..'clickexplode'
prefix..'unclickexplode'
prefix..'cakeday'
prefix..'control' then -- really funny ngl (scv1)
prefix..'ncontrol' then -- really funny ngl (cmdpi)
prefix..'iceblock' then -- pr script
prefix..'glitch' then -- noobsploit
prefix..'headrise' then -- jotunnheim
prefix..'headroot' then -- jotunnheim
prefix..'skybox' then -- jotunnheim
prefix..'amputate' then -- jotunnheim
prefix..'icetower' then -- jotunnheim
prefix..'coconut' then -- noobsploit
prefix..'cube' then -- cmdv3/pi
prefix..'tank' then -- thomas the tank engine - from yt video
prefix..'ufo' then -- ufo!!! scv1
prefix..'rat' then -- scv1
prefix..'titan' then -- yeah im adding scv1 cmds lol
prefix..'speaker' then -- yeah im adding scv1 cmds lol
prefix..'dogrock' then -- noobsploit/shazam
prefix..'rdogrock' then -- noobsploit/shazam
prefix..'taxi' then -- kohlsnoob
prefix..'smoothie' then -- kohlsnoob
prefix..'tnt' then -- sHaZam!
prefix..'headfloat' then -- yeah im adding scv1 cmds lol
prefix..'space' then -- kohls true anti kill
prefix..'tripin' then -- pr
prefix..'ascend' then -- kohlsnoob
prefix..'bed' then -- noobsploit techno
prefix..'kitten' then -- nak3d would get tagged, inspired by simplekah
prefix..'smack' then -- pr
prefix..'dumb' then -- pr
prefix..'bend' then -- pr/cxodek script
prefix..'ruin' then -- pr/vitalux script
prefix..'fspin' then -- kohlsnoob
prefix..'yeet' then -- kohlsnoob
prefix..'creeper' then -- kohlsnoob
prefix..'gbreak' then -- pr script
prefix..'antidisco'
prefix..'unantidisco'
prefix..'antiflash'
prefix..'unantiflash'
prefix..'antifogend'
prefix..'unantifogend'
prefix..'antiilight'
prefix..'unantiilight'
prefix..'antifogstart'
prefix..'unantifogstart'
prefix..'antifogc'
prefix..'unantifogc'
prefix..'antitime'
prefix..'unantitime'
prefix..'antiamb'
prefix..'unantiamb'
prefix..'antitrip'
prefix..'unantitrip'
prefix..'antiegg'
prefix..'unantiegg'
prefix..'antibright'
prefix..'unantibright'
prefix..'antioutamb'
prefix..'unantioutamb'
prefix..'adv'
prefix..'cadv'
prefix..'ipboom'
prefix..'logspam'
prefix..'logtrap' then -- scv1
prefix..'logmode'
prefix..'persons'
prefix..'unpersons'
prefix..'peadmin'
prefix..'unpeadmin'
prefix..'tptool'
prefix..'supercmd'
prefix..'supert'
prefix..'spamt'
prefix..'unspamt'
prefix..'chatz'
prefix..'spamw'
prefix..'spamwait'
prefix..'spamoff'
prefix..'spamon'
prefix..'cbtools'
prefix..'ecrash'
prefix..'dicrash'
prefix..'fredcrash'
prefix..'chcrash'
prefix..'rockmap'
prefix..'stonemap'
prefix..'hammer'
prefix..'platform'
prefix..'noplatform'
prefix..'float'
prefix..'unfloat'
prefix..'icemap'
prefix..'byp' then -- created by tech-187, open source on his repo :)
prefix..'nbyp' then -- my version (might work better)
prefix..'sregen'
prefix..'unsregen'
prefix..'autogpc'
prefix..'unautogpc'
prefix..'padban'
prefix..'unpadban'
prefix..'padreinf'
prefix..'unpadreinf'
prefix..'qattach'
prefix..'biglogs'
prefix..'regen'
prefix..'house'
prefix..'spawn'
prefix..'hhouse'
prefix..'phelp'
prefix..'void' then -- kohlsnoob
prefix..'execute'
prefix..'announce'
prefix..'cannounce' then -- inspired by scv3-var
prefix..'shlong'
prefix..'unshlong'
prefix..'dncycle'
prefix..'undncycle'
prefix..'arena'
prefix..'prefix'
'cprefix'
prefix..'pmap'
prefix..'paintmap'
prefix..'messpaint'
prefix..'rbgmap'
prefix..'rmap'
prefix..'rbase'
prefix..'rfog'
prefix..'unrmap'
prefix..'unrbase'
prefix..'unrfog'
prefix..'autoafk'
prefix..'unautoafk'
prefix..'antilag'
prefix..'unantilag'
prefix..'capfps'
prefix..'alladmin'
prefix..'unalladmin'
prefix..'nok'
prefix..'2nok'
prefix..'3nok'
prefix..'tnok'
prefix..'untnok'
prefix..'getping'
prefix..'autogb'
prefix..'unautogb'
prefix..'qpunish' then -- idea from zercon
prefix..'spunish' then -- ii's admin
prefix..'gpunish' then -- ii's admin
prefix..'ungearban'
prefix..'gearban'
prefix..'rail'
prefix..'lemonman'
prefix..'laser'
prefix..'surround'
prefix..'rnuke'
prefix..'dnuke'
prefix..'jnuke'
prefix..'rcannon'
prefix..'wrcannon'
prefix..'uncannon'
prefix..'astrike'
prefix..'unastrike'
prefix..'skcraze'
prefix..'unskcraze'
prefix..'weld'
prefix..'nweld'
prefix..'hfreeze'
prefix..'tattach'
prefix..'acton'
prefix..'rfgun'
prefix..'unrfgun'
prefix..'sjail'
prefix..'nuke'
prefix..'age'
prefix..'jdate'
prefix..'dkick' then -- buggy!
prefix..'undkick' then -- buggy!
prefix..'slag' then -- buggy!
prefix..'nslag' then -- buggy!
prefix..'rpaintui'
prefix..'sspawn' then -- save spawn
prefix..'cpos' then -- print current pos
prefix..'gsspawn' then -- go to saved spawn
prefix..'frespawn' then -- force respawn (broken)
prefix..'mrespawn' then -- force respawn (broken)
prefix..'dummy'
prefix..'ffix'
prefix..'rejoin'
prefix..'rj'
prefix..'autorj'
prefix..'unautorj'
prefix..'prj'
prefix..'prejoin'
prefix..'shop'
prefix..'serverhop'
prefix..'iyshop'
prefix..'scshop'
prefix..'rshop'
prefix..'infjump'
prefix..'uninfjump'
prefix..'speed'
prefix..'editsp'
prefix..'uneditsp'
prefix..'jp'
prefix..'editjp'
prefix..'uneditjp'
prefix..'minzoom'
prefix..'maxzoom'
prefix..'hlth'
prefix..'fov'
prefix..'grav'
prefix..'unlockws'
prefix..'lockws'
prefix..'noclip'
prefix..'clip'
prefix..'ufly'
prefix..'isc'
prefix..'checkc'
prefix..'breakanims'
prefix..'nocam'
prefix..'wbcam'
prefix..'wfcam'
prefix..'breakcam'
prefix..'fixcam'
prefix..'fixvelo'
prefix..'obpfixv'
prefix..'bpfixv'
prefix..'flipbp'
prefix..'fakebp'
prefix..'nofakebp'
prefix..'fixcol'
prefix..'fixgrav'
prefix..'novelo'
prefix..'breakvelo'
prefix..'loopgrab'
prefix..'unloopgrab'
prefix..'fastpads'
prefix..'2loopgrab'
prefix..'2unloopgrab'
prefix..'perm'
prefix..'2perm'
prefix..'unperm'
prefix..'2unperm'
prefix..'allpads'
prefix..'checkbp'
prefix..'gotosky'
prefix..'ungearme'
prefix..'nowater'
prefix..'watermap'
prefix..'fixpaint'
prefix..'anticrash'
prefix..'unanticrash'
prefix..'emranticrash'
prefix..'unemranticrash'
prefix..'antigs' then -- what is this?
prefix..'unantigs'
prefix..'antipaint'
prefix..'unantipaint'
prefix..'antigear'
prefix..'unantigear'
prefix..'antigb'
prefix..'unantigb'
prefix..'2antiattach2'
prefix..'2unantiattach'
prefix..'antiattach'
prefix..'unantiattach'
prefix..'antifling'
prefix..'unantifling'
prefix..'noblt'
prefix..'unnoblt'
prefix..'antiray'
prefix..'unantiray'
prefix..'novoid'
prefix..'fixvoid'
prefix..'cvoid'
prefix..'pinglogs'
prefix..'unpinglogs'
prefix..'antilogs'
prefix..'unantilogs'
prefix..'pingcsys'
prefix..'unpingcsys'
prefix..'noobdetect'
prefix..'unnoobdetect'
prefix..'antiblind'
prefix..'unantiblind'
prefix..'antiaddon'
prefix..'unantiaddon'
prefix..'anticlone'
prefix..'unanticlone'
prefix..'antidog'
prefix..'unantidog'
prefix..'antifire'
prefix..'unantifire'
prefix..'antifreeze'
prefix..'unantifreeze'
prefix..'antiff'
prefix..'unantiff'
prefix..'antiglow'
prefix..'unantiglow'
prefix..'antihc'
prefix..'unantihc'
prefix..'antijail'
prefix..'unantijail'
prefix..'antijump'
prefix..'unantijump'
prefix..'antikill'
prefix..'unantikill'
prefix..'antifly' then -- forgot to add this to the list lmao
prefix..'unantifly' then -- forgot to add this to the list lmao
prefix..'antinoc' then -- yes
prefix..'unantinoc' then -- yes
prefix..'antichar'
prefix..'unantichar'
prefix..'antimsg'
prefix..'unantimsg'
prefix..'antitp'
prefix..'unantitp'
prefix..'antivoid'
prefix..'unantivoid'
prefix..'antisky'
prefix..'unantisky'
prefix..'antiname'
prefix..'unantiname'
prefix..'antiparticles'
prefix..'unantiparticles'
prefix..'antipunish'
prefix..'unantipunish'
prefix..'antirocket'
prefix..'unantirocket'
prefix..'antikick'
prefix..'unantikick'
prefix..'antit'
prefix..'unantit'
prefix..'antisit'
prefix..'unantisit'
prefix..'antiseizure'
prefix..'unantiseizure'
prefix..'antismoke'
prefix..'unantismoke'
prefix..'antisparkles'
prefix..'unantisparkles'
prefix..'antispeed'
prefix..'unantispeed'
prefix..'antispin'
prefix..'unantispin'
prefix..'antistun'
prefix..'unantistun'
prefix..'antistg'
prefix..'unantistg'
prefix..'antiswag'
prefix..'unantiswag'
prefix..'antichat'
prefix..'unantichat'
prefix..'mkick' then -- haha i found it
prefix..'unmkick'
prefix..'pkick'
prefix..'unpkick'
prefix..'lkick'
prefix..'unlkick'
prefix..'autoff'
prefix..'unautoff'
prefix..'autogod'
prefix..'unautogod'
prefix..'autochar'
prefix..'unautochar'
prefix..'freerobux'
prefix..'reserver' then -- kohlsnoob and betterpersons (tech)
prefix..'devcmd'
prefix..'discord'
prefix..'buy'
prefix..'purchase'
prefix..'r6'
prefix..'r15'
prefix..'dance'
prefix..'undance'
prefix..'spasm'
prefix..'unspasm'
prefix..'headthrow'
prefix..'headsit'
prefix..'carpet'
prefix..'uncarpet'
prefix..'bang'
prefix..'unbang'
prefix..'mutebb' then -- yes this isn't a loop, i'm lazy
prefix..'unmutebb'
prefix..'view'
prefix..'unview'
prefix..'spin'
prefix..'unspin'
prefix..'swim'
prefix..'unswim'
prefix..'tswim'
prefix..'fling'
prefix..'unfling'
prefix..'freecam'
prefix..'unfreecam'
prefix..'fcspeed'
prefix..'stopanims'
prefix..'noanim'
prefix..'reanim'
prefix..'sit'
prefix..'unsit'
prefix..'trip'
prefix..'animsp'
prefix..'delvelo'
prefix..'bvelo'
prefix..'cfly'
prefix..'uncfly'
prefix..'cfspeed'
prefix..'fly'
prefix..'unfly'
prefix..'fspeed'
prefix..'qefly'
prefix..'tfly'
prefix..'weaken'
prefix..'unweaken'
prefix..'strengthen'
prefix..'unstrengthen'
prefix then -- so THEY don't use YOU!
prefix..'hmode'
prefix..'hcmds'
