while wait(.5) do
    if notover then return end
    notover = true
    local folder = workspace.Terrain._Game.Folder
    game.Players:Chat("clr")
    repeat task.wait() until not folder:FindFirstChild("Sound")	
    game.Players:Chat("time -")
    game.Players:Chat("fogcolor 0 0 0")
    game.Players:Chat("fogend 500")
    game.Players:Chat("music 1840006904")
    repeat task.wait() until folder:FindFirstChild("Sound") and folder:FindFirstChild("Sound").Playing
    local sound = folder:FindFirstChild("Sound")
    task.spawn(function() 
    if sound.TimePosition == 0 then repeat task.wait() until not sound.TimePosition == 0 end
    if sound.TimePosition ~= 0 then repeat task.wait() until not sound.TimePosition == 0 end
    game.Players:Chat("fix")
    game.Players:Chat("clr")
    end)
    wait(7.5)
    game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\nI had a friend");wait(2)
    game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\nHe was all so lovely");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nHe listens so wellll and pays so much attention to me");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nHe listens so wellll and pays so much attention to me");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nI tell him bout who I loooooooooooooove                                                                                                            ");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                            He gives me advisive stuff");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAnd whenever it was rough           ");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n           He keeps me back into touch");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n One day he");wait(1)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                            tooooooooold");wait(1)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                         me");wait(1.2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSowwy            ");wait(1)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                  but           ");wait(.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                               he           ");wait(.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                            just           ");wait(.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                            had           ");wait(.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                enough           ");wait(1)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nHe said he looooooooooooooved                                                                                                            ");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nHe said he looooooooooooooved                                                                                                            ")
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h Hello there everyone\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nme                                                ");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                            That's when I told him");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nbaby stop");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nbaby stop                                                                                                            ");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                            baby stop");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nbaby stop                                                                                                            ");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                            ohhhhhhhhhhh");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("disco") -- drop
    wait(.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noooooooooowooooooooooooowoooooooooooowooooooooooowoooooooooo");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noooooooooowooooooooooooowoooooooooooowooooooooooowoooooooooo");wait(1.7)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n I don't wanna break your");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h No not really\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                    haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawaaaaaaaaaaaat");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h What are you talking about?\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nbut");wait(.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noooooooooowooooooooooooowoooooooooooowooooooooooowoooooooooo");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noooooooooowooooooooooooowoooooooooooowooooooooooowoooooooooo");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n I think we're better as");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h You kidding, bro?\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                    freeeeeeeeeeeeeeeeeeeeeeheeeeeeeeeeeeeeeeeeeeeeeeeeeeendddddsssssssss");wait(2.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noooooooooowooooooooooooowoooooooooooowooooooooooowoooooooooo");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noooooooooowooooooooooooowoooooooooooowooooooooooowoooooooooo");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n I don't wanna break your");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h No not really\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                    haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawaaaaaaaaaaaat");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h What are you talking about?\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nbut");wait(.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noooooooooowooooooooooooowoooooooooooowooooooooooowoooooooooo");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noooooooooowooooooooooooowoooooooooooowooooooooooowoooooooooo");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n I think we're better as");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h You kidding, bro?\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                    freeeeeeeeeeeeeeeeeeeeeeheeeeeeeeeeeeeeeeeeeeeeeeeeeeendddddsssssssss");wait(2.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("fix") -- drop end
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("time -")
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("fogcolor 0 0 0")
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("fogend 500")
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\nIt could get tricky");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\nIt could get tricky");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDon't wanna get tricky");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h My character fell into a pit\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nStickyickyicky");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("disco the drop again") -- drop
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\nIt could get tricky");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\nThis could get tricky");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\nIt could get tricky");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nStickyickyicky yoooo");wait(1.5) -- plus .5 added since the second drop goes earlier
    --[[
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("disco the drop again") -- drop
    wait(.5)]]
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("fogend 190")
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h The song is nice\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noooooooooowooooooooooooowoooooooooooowooooooooooowoooooooooo");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h It's fye\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noooooooooowooooooooooooowoooooooooooowooooooooooowoooooooooo");wait(1.7)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h more then fya\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n I don't wanna break your");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h No not really\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                    haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawaaaaaaaaaaaat");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h What are you talking about?\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nbut");wait(.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noooooooooowooooooooooooowoooooooooooowooooooooooowoooooooooo");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noooooooooowooooooooooooowoooooooooooowooooooooooowoooooooooo");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n I think we're better as");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h You kidding, bro?\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                    freeeeeeeeeeeeeeeeeeeeeeheeeeeeeeeeeeeeeeeeeeeeeeeeeeendddddsssssssss");wait(2.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noooooooooowooooooooooooowoooooooooooowooooooooooowoooooooooo");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noooooooooowooooooooooooowoooooooooooowooooooooooowoooooooooo");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n I don't wanna break your");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h No not really\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                    haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawaaaaaaaaaaaat");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h What are you talking about?\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nbut");wait(.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noooooooooowooooooooooooowoooooooooooowooooooooooowoooooooooo");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noooooooooowooooooooooooowoooooooooooowooooooooooowoooooooooo");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n I think we're better as");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h You kidding, bro?\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                    freeeeeeeeeeeeeeeeeeeeeeheeeeeeeeeeeeeeeeeeeeeeeeeeeeendddddsssssssss");wait(2.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("fix") -- drop end
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("time -")
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("fogcolor 0 0 0")
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("fogend 500")
    wait(1)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n One day he");wait(1)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                            tooooooooold");wait(1)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                         me");wait(1.2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSowwy            ");wait(1)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                  but           ");wait(.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                               he           ");wait(.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                            just           ");wait(.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                            had           ");wait(.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                enough           ");wait(1)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nHe said he looooooooooooooved                                                                                                            ");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nHe said he looooooooooooooved                                                                                                            ")
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h Hello there everyone\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nme                                                ");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                               That's when I told him baby stop");wait(3)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("disco the drop AGAIN") -- drop
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\nIt could get tricky");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\nIt could get tricky");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDon't wanna get tricky");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h My character fell into a pit\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nStickyickyicky");wait(1.5)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\nIt could get tricky");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\nThis could get tricky");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\nIt could get tricky");wait(2)
    if not folder:FindFirstChild("Sound").Playing then notover = false return end;game.Players:Chat("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nStickyickyicky yoooo")
    wait(5)
    notover = false
end
