local function c(m)
    game.Players:Chat(m)
end

local folder = workspace.Terrain._Game.Folder
c("clr")
repeat task.wait() until not folder:FindFirstChild("Sound")	
c("time -")
;c("fogcolor 0 0 0")
c("fogend 500")
c("music 15689455422")
repeat task.wait() until folder:FindFirstChild("Sound") and folder:FindFirstChild("Sound").Playing
local sound = folder:FindFirstChild("Sound")

function b()
    if not folder:FindFirstChild("Sound").Playing then return end
end

task.spawn(function() 
if sound.TimePosition == 0 then repeat task.wait() until not sound.TimePosition == 0 end
if sound.TimePosition ~= 0 then repeat task.wait() until not sound.TimePosition == 0 end
b();c("fix");
b();c("clr");
end)
getgenv().bassline = true

-- LYRICS
task.delay(5, function() 
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nI looooveee");wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nI looooveee") -- The doing things withadditional text at the start is to prevent it from tagging.
    b();c("h doing things with \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                             youu");wait(1.5)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n you love");wait(.5)
    b();c("h doing things with \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                       me");wait(.25)
    b();c("h doing things with \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                      too");wait(.25)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\ntoo                                                                                                                                                        ");wait(.25)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                                                                        too");wait(.25)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\ntoo                                                                                                                                                        ");wait(.25)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                                                                        too");wait(.25)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\ntoo");wait(.2)
    wait(.6)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nBut whattt");wait(1.4)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nBut whattt")
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                a shame");wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n we are");wait(.5)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n we are")
    b();c("h doing things with \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                             far away");wait(2)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nWhat we");wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                             can do");wait(1.5)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n Love");wait(.25)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                              equals");wait(.25)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                            me");wait(.25)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                          and");wait(.25)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nyouuu");wait(.5)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nyou                                                                                                                                                        ");wait(.25)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                                                                        you");wait(.25)
    wait(.6)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nI cannot");wait(1.4)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nI cannot")
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                        waittt");wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n I don't");wait(.25)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                      want");wait(.25)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                    to");wait(.25)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                               be");wait(.25)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                            late")
    wait(2)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nI don't want to be late");wait(3)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n I don't want others baby, I need you to stay");wait(5.5)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n You are my favorite person I have ever met");wait(5)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n I can't hold back my feelings");wait(3)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n So I");wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                      dream");wait(.5)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                         of");wait(.25)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                    a");wait(.25)
    b();c("h what time is it \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                 daaaaaaaaaaaaaaaaaaaaaaayyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyt")
    wait(2.5)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nYou're my                                                                                                                                                        ");wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nYou're my                                                                                                                                                        ")
    b();c("h This is something that I\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                        love                                                                                                                                                        ")
    wait(.5)
    b();c("reset all")-- Removes the regular h text since that stays on screen for quite a while
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n Thinkin' bout                                                                                                                                                        ");wait(1.5)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n you every day and night                                                                                                                                                        ");wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                                                                        You're my");wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                                                                        You're my")
    b();c("h This is something that I\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                                                                                                love")
    wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                                                                         have no doubt");wait(1.5)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                                                                         like diamond caught my eye");wait(.5)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                                                                         like diamond caught my eye");wait(2.5)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n You're a thief");wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n  stole my haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa (heart)");wait(2)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n   I cannot wait");wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n       Always knew that you were my fate");wait(6)
    --b();c("h test")
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nYou're my                                                                                                                                                        ");wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nYou're my                                                                                                                                                        ")
    b();c("h This is something that I\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                        love                                                                                                                                                        ")
    wait(.5)
    b();c("reset all") -- Removes the regular h text since that stays on screen for quite a while (again)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n Thinkin' bout                                                                                                                                                        ");wait(1.5)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n you every day and night                                                                                                                                                        ");wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                                                                        You're my");wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                                                                        You're my")
    b();c("h This is something that I\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                                                                                                love")
    wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                                                                         have no doubt");wait(1.5)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                                                                         like diamond caught my eye");wait(.5)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                                                                                                                         like diamond caught my eye");wait(2.5)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n You're a thief");wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n  stole my haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa (heart)");wait(2)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n   I cannot wait");wait(1)
    b();c("h \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n       Always knew that you were my fate");wait(6)
end)

wait(5.5)
task.spawn(function()
    task.delay(9.8, function() 
        -- BASS ALTERNATIVE
        b();c("fogcolor 255 255 0")
        b();c("fogend 250")
        wait(.2)
        b();c("fogcolor 0 0 0")
        b();c("fogend 500")
        wait(10)
        for i = 1, 2 do
            b();c("fogcolor 255 255 0")
            b();c("fogend 250")
            wait(.2)
            b();c("fogcolor 0 0 0")
            b();c("fogend 500")
            wait(.2)
        end
        wait(10.4)
        b();c("fogcolor 255 255 0")
        b();c("fogend 250")
        wait(.2)
        b();c("fogcolor 0 0 0")
        b();c("fogend 500")
        wait(9.8)
        for i = 1, 2 do
            b();c("fogcolor 255 255 0")
            b();c("fogend 250")
            wait(.1)
            b();c("fogcolor 0 0 0")
            b();c("fogend 500")
            wait(.1)
        end
        for i = 1, 2 do
            b();c("fogcolor 255 255 0")
            b();c("fogend 250")
            wait(.2)
            b();c("fogcolor 0 0 0")
            b();c("fogend 500")
            wait(.2)
        end
        wait(9.8)
        b();c("fogcolor 255 255 0")
        b();c("fogend 250")
        wait(.2)
        b();c("fogcolor 0 0 0")
        b();c("fogend 500")
        wait(10)
        for i = 1, 2 do
            b();c("fogcolor 255 255 0")
            b();c("fogend 250")
            wait(.2)
            b();c("fogcolor 0 0 0")
            b();c("fogend 500")
            wait(.2)
        end
    end)
    -- BASSLINE MAIN
    while bassline do
        b();c("fogcolor 255 255 0")
        b();c("fogend 250")
        wait(.65)
        b();c("fogcolor 0 0 0")
        b();c("fogend 500")
        wait(4.65)
    end
end)
